version: '3.6'
services:
  gitlab:
    image: gitlab/gitlab-ce:16.11.8-ce.0
    container_name: gitlab
    restart: always
    hostname: 'gitlab.internal.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://127.0.0.1'
    ports:
      - '5020:80'
      # - '443:443'
      - '226:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'
    networks:
      - gitlab-network

  # RUNNER
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    restart: always
    container_name: gitlab-runner
    hostname: gitlab-runner
    depends_on:
      - gitlab
    volumes:
     - ./config/gitlab-runner:/etc/gitlab-runner
     - /var/run/docker.sock:/var/run/docker.sock
    networks:
        - gitlab-network

networks:
  gitlab-network:
    name: gitlab-network




# version: "3.6"
# services:
#   gitlab:
#     image: gitlab/gitlab-ce:16.11.8-ce.0
#     container_name: gitlab
#     restart: always
#     hostname: 'gitlab.internal.com'
#     ports:
#       - "22:22"
#       - "5060:80"
#       # - "443:443"
#     volumes:
#       - $GITLAB_HOME/data:/var/opt/gitlab
#       - $GITLAB_HOME/logs:/var/log/gitlab
#       - $GITLAB_HOME/config:/etc/gitlab
#     shm_size: '256m'
#     environment:
#       GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
#     configs:
#       - source: gitlab
#         target: /omnibus_config.rb
#     secrets:
#       - gitlab_root_password
#   # gitlab-runner:
#   #   image: gitlab/gitlab-runner:alpine
#   #   deploy:
#   #     mode: replicated
#   #     replicas: 4
# configs:
#   gitlab:
#     file: ./gitlab.rb
# secrets:
#   gitlab_root_password:
#     file: ./root_password.txt